### ISSUE TITLE
[Init]: Set up the app structure and routes

### ISSUE THREAD

**Issue by abhishek-dev-works** [abhishek-dev-works/e-commerce-next-js#1]
We need to setup the routes for all pages , define the basic structure of the app and configure deployments.
As goes for the app design please refer to the below link

https://demo-robin.myshopify.com/

**Comment by hritikk7** [comment]
[example-furniture-web-page](https://furniro-ecommerce-blue.vercel.app/) this could be a very good resource and aligns with our vision
source code : [here{github}]( https://github.com/PiusLucky/furniro-ecommerce)
